// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLxaPs6ESo7qvUIG6rgF5bTWihm0f6tsk',
    appId: '1:222422438347:web:1e57bb874bcb53a747a64e',
    messagingSenderId: '222422438347',
    projectId: 'employee-management-c96da',
    authDomain: 'employee-management-c96da.firebaseapp.com',
    storageBucket: 'employee-management-c96da.appspot.com',
    measurementId: 'G-FZPMVR01F1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOQ5tn5Nzaa7OuZhKI-JoSGvCIOI-OoOo',
    appId: '1:222422438347:android:7628c35a2e0d815d47a64e',
    messagingSenderId: '222422438347',
    projectId: 'employee-management-c96da',
    storageBucket: 'employee-management-c96da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBzovZGLmtCkcIxqZ2MHaXjNqNvhBpBDg',
    appId: '1:222422438347:ios:75984ecac9d5684147a64e',
    messagingSenderId: '222422438347',
    projectId: 'employee-management-c96da',
    storageBucket: 'employee-management-c96da.appspot.com',
    iosBundleId: 'com.example.machinetestWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBzovZGLmtCkcIxqZ2MHaXjNqNvhBpBDg',
    appId: '1:222422438347:ios:75984ecac9d5684147a64e',
    messagingSenderId: '222422438347',
    projectId: 'employee-management-c96da',
    storageBucket: 'employee-management-c96da.appspot.com',
    iosBundleId: 'com.example.machinetestWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLxaPs6ESo7qvUIG6rgF5bTWihm0f6tsk',
    appId: '1:222422438347:web:bd6448a45809676247a64e',
    messagingSenderId: '222422438347',
    projectId: 'employee-management-c96da',
    authDomain: 'employee-management-c96da.firebaseapp.com',
    storageBucket: 'employee-management-c96da.appspot.com',
    measurementId: 'G-166C0BJP6T',
  );

}